import React from 'react';

import { Noto_Sans_JP } from 'next/font/google';

import type { Metadata } from 'next';

import './globals.css';

import { AuthProvider } from '@/context/authContext';
import Header from '@/features/Header';

const noto = Noto_Sans_JP({
	display: 'swap',
	preload: false,
	variable: '--font-noto',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html
			lang='ja'
			className={String(noto.variable)}
		>
			<body>
				<React.StrictMode>
					<AuthProvider>
						<Header></Header>
						{children}
					</AuthProvider>
				</React.StrictMode>
			</body>
		</html>
	);
}
